### ISSUE TITLE
Auto tagging

### ISSUE THREAD

**Issue by jqnatividad** [stadt-karlsruhe/ckanext-extractor#1]
Consider integrating with http://api.reegle.info/ to automatically create tags for concepts, places, and other entities.

Some more context - actually prototyped integration with Semantic Mediawiki and it worked surprisingly well even for non-cleantech related content.  It was still able to recognize generic concepts, places, and people.  And the best part is the auto-tagging API is free.

**Comment by torfsen** [comment]
Thanks for the suggestions! Currently we don't have plans for directly integrating the Climate Tagger API into _ckanext-extractor_, however the next release will contain the possibility of [adding your own postprocessing handlers for extracted metadata](https://github.com/stadt-karlsruhe/ckanext-extractor#postprocessing-extraction-results). That should make it easy to integrate the Climate Tagger API and similar services.

**Comment by torfsen** [comment]
[Version 0.2](https://github.com/stadt-karlsruhe/ckanext-extractor/releases/tag/v0.2.0) was just released. It contains the support for custom postprocessing mentioned above.
