### ISSUE TITLE
Error for PDF Resources

### ISSUE THREAD

**Issue by gjackson12** [stadt-karlsruhe/ckanext-extractor#11]
When I attempt to create a resource with a PDF file I am receiving the following error: 
raised unexpected: `SearchIndexError("Solr returned an error: (u'Solr responded with an error (HTTP 400): [Reason: ERROR: [doc=6b8e5b3b06fb3097149ebc2caffa7ffa] multiple values encountered for non multiValued field ckanext-extractor_b7e8d049-9b51-4c98-8d09-33b4879a45d7_x-parsed-by: [org.apache.tika.parser.DefaultParser, org.apache.tika.parser.pdf.PDFParser]]',)",) the following error: `

Any thoughts?

**Comment by torfsen** [comment]
Thanks for your report, @gjackson12!

It looks like the extracted metadata contains multiple values for the same field `x-parsed-by`, and that causes errors for Solr. I will take a look at it once I find time.

**Comment by torfsen** [comment]
This has been fixed on master. Multiple values for the same field are now collapsed into a single value.
