### ISSUE TITLE
extracter conflicts with a before_index method

### ISSUE THREAD

**Issue by mystycs** [stadt-karlsruhe/ckanext-extractor#15]
I have the method before_index in an extension which takes a multivalued field and helps sort it in slor for tags so instead of appearing as a list they appear individually.

Basically, business_area looks like ["tag1", "tag2", "tag3" ]

If there are no tags its just an empty list "[]"

```
    def before_index(self, data_dict):
	print(data_dict)
	#print(json.loads(data_dict.get('business_area', '[]')))
	if data_dict.get('business_area'):
            data_dict['business_area'] = json.loads(data_dict.get('business_area', '[]'))
	return data_dict
```

The problem is when extractor picks up it keeps getting this stack trace on every push. It keeps saying
TypeError: expected string or buffer

If I remove that method before_index all together it works fine and I don't get this error. 

Why does extractor keep calling this in a separate extension? And is there any way to fix it from erroring that? Also why is it giving errors? This method works fine besides extractor complaining about it.
```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/rq/worker.py", line 588, in perform_job
    rv = job.perform()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/rq/job.py", line 498, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/usr/lib/ckan/default/src/ckanext-extractor/ckanext/extractor/tasks.py", line 202, in extract
    index_for('package').update_dict(pkg_dict)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/index.py", line 101, in update_dict
    self.index_package(pkg_dict, defer_commit)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/search/index.py", line 278, in index_package
    pkg_dict = item.before_index(pkg_dict)
  File "/usr/lib/ckan/default/src/ckanext-datasettheme/ckanext/datasettheme/plugin.py", line 99, in before_index
    data_dict['business_area'] = json.loads(data_dict.get('business_area', '[]'))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

```

**Comment by mystycs** [comment]
FYI: This happens in the ckan-worker background job

**Comment by mystycs** [comment]
Looks like it was an issue with how the solr index was updated, it was running a bunch of other stuff like before_index etc. I used this instead in tasks.py to update the search-index line 110  https://github.com/stadt-karlsruhe/ckanext-extractor/blob/811b3886a043a838dd7547bdaa05e3d52efd9eb5/ckanext/extractor/tasks.py#L110

ckan.lib.cli.SearchIndexCommand('SearchIndexCommand').rebuild(res_dict['package_id'])

**Comment by torfsen** [comment]
@mystycs It is intended that implementations of `before_index` in all active plugins are run when ckanext-extractor updates Solr's index for a package. So if you have a `before_index` implementation that works without ckanext-extractor, then it should be called when ckanext-extractor runs and that call shouldn't fail due to something that ckanext-extractor does.

Judging from your stacktrace, `data_dict.get('business_area', '[]')` doesn't return a string for you. Have you checked what type that value actually has?

**Comment by mystycs** [comment]
It inputs a multi valued checkbox from https://github.com/ckan/ckanext-scheming

So it looks like ["tag1", "tag2", "tag3" ]. This is so that tags rendered on the dataset page dont look like lists but rather are split up separately.

**Comment by mystycs** [comment]
But using my search index update method did the trick. And im having no issues. So this may just be a use case for me.
