### ISSUE TITLE
Migration to ckan 2.7 background tasks

### ISSUE THREAD

**Issue by jbothma** [stadt-karlsruhe/ckanext-extractor#9]
Do you have any plans to support [the new background jobs system](http://docs.ckan.org/en/ckan-2.7.0/maintaining/background-tasks.html) soon?

**Comment by torfsen** [comment]
Support is planned, yes. However we currently don't have a fixed date for it, yet.

Note that the old Celery-based system is deprecated but still supported in CKAN 2.7.

**Comment by jbothma** [comment]
Cool - yeah I'm mainly interested in this to reduce the dependencies of my cluster. Not a big deal. Thanks!

**Comment by torfsen** [comment]
I'm reopening this issue until support for the new background tasks is actually implemented.

**Comment by torfsen** [comment]
This has been fixed and released as part of [0.4.0](https://github.com/stadt-karlsruhe/ckanext-extractor/releases/tag/v0.4.0).
